#!/bin/bash

echo "......................................................"
echo "gateway installing"
echo "......................................................"

systemctl enable gateway
systemctl start gateway
